const menu = [
  {
    id: 1,
    title: "Cafe Late",
    category: "Hot Beverages",
    price: '',
    img: "./images/cafe-latte.jpeg",
    desc: `Single - Ksh. 250, Double - Ksh. 300`,
  },
  {
    id: 18,
    title: "Cappuccino",
    category: "Hot Beverages",
    price: '',
    img: "./images/cupa.webp",
    desc: `Single - Ksh. 250, Double - Ksh. 300`,
  },
  {
    id: 19,
    title: "Espresso",
    category: "Hot Beverages",
    price: '',
    img: "./images/espresso.webp",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 20,
    title: "House Coffee (White or Black)",
    category: "Hot Beverages",
    price: '',
    img: "./images/house-coffee.jpg",
    desc: `Single - Ksh. 200, Double - Ksh. 250`,
  },
  {
    id: 21,
    title: "Caramel Macchiato",
    category: "Hot Beverages",
    price: '',
    img: "./images/caramel.jpg",
    desc: `Single - Ksh. 250, Double - Ksh. 350`,
  },
  {
    id: 22,
    title: "Hazelnut Latte",
    category: "Hot Beverages",
    price: '',
    img: "./images/hazelnut.jpeg",
    desc: `Single - Ksh. 300, Double - Ksh. 350`,
  },
  {
    id: 23,
    title: "Mocha",
    category: "Hot Beverages",
    price: '',
    img: "./images/mocha.png",
    desc: `Single - Ksh. 250, Double - Ksh. 300`,
  },
  {
    id: 24,
    title: "Peppermint Mocha",
    category: "Hot Beverages",
    price: '',
    img: "./images/peppermint.jpg",
    desc: `Single - Ksh. 300, Double - Ksh. 350`,
  },
  {
    id: 25,
    title: "Vanilla Latte",
    category: "Hot Beverages",
    price: '',
    img: "./images/Vanilla-latte.jpg",
    desc: `Single - Ksh. 300, Double - Ksh. 350`,
  },
  {
    id: 26,
    title: "Americano",
    category: "Hot Beverages",
    price: '',
    img: "./images/americano.webp",
    desc: `Single - Ksh. 200, Double - Ksh. 250`,
  },
  {
    id: 27,
    title: "Hot Chocolate (White or Black)",
    category: "Hot Beverages",
    price: '',
    img: "./images/hotchoco.jpg",
    desc: `Single - Ksh. 250, Double - Ksh. 300`,
  },
  {
    id: 28,
    title: "Hazelnut Chocolate",
    category: "Hot Beverages",
    price: '',
    img: "./images/hazelchoco.webp",
    desc: `Single - Ksh. 250, Double - Ksh. 300`,
  },
  {
    id: 29,
    title: "Strawberry Milk",
    category: "Hot Beverages",
    price: '',
    img: "./images/strawberry.jpg",
    desc: `Single - Ksh. 200, Double - Ksh. 250`,
  },
  {
    id: 30,
    title: "Caramel Milk",
    category: "Hot Beverages",
    price: '',
    img: "./images/caramel-milk.webp",
    desc: `Single - Ksh. 200, Double - Ksh. 250`,
  },
  {
    id: 31,
    title: "Tumeric Milk",
    category: "Hot Beverages",
    price: '',
    img: "./images/tumeric.jpg",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 32,
    title: "Regular Tea (White or Black)",
    category: "Hot Beverages",
    price: '',
    img: "./images/tea.jpg",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 33,
    title: "Masala Tea",
    category: "Hot Beverages",
    price: '',
    img: "./images/masala-tea.jpg",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 34,
    title: "Lemon Tea",
    category: "Hot Beverages",
    price: '',
    img: "./images/lemon-tea.jpg",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 35,
    title: "Ginger Tea",
    category: "Hot Beverages",
    price: '',
    img: "./images/ginger-tea.jpg",
    desc: `Single - Ksh. 150, Double - Ksh. 200`,
  },
  {
    id: 2,
    title: "Camomile Tea (Double)",
    category: "Hot Beverages",
    price: 200,
    img: "./images/Camomile-Tea.webp",
    desc: `1 egg, 1 sausage, baked beans, tea/ fruit slices, juice `,
  },
  {
    id: 3,
    title: "Fresh Dawa",
    category: "Hot Beverages",
    price: 250,
    img: "./images/CJs.jpg",
    // img: "./images/item-3.jpeg",
    desc: `Mint Ginger Lemon and Honey Spiced with Cinnamon`,
  },
  {
    id: 4,
    title: "Herbal Teas",
    category: "Hot Beverages",
    price: 400,
    img: "./images/herbal-teas.jpg",
    desc: `Ask your server. ' `,
  },
  {
    id: 5,
    title: "Carrot Beetroot",
    category: "Cold Drinks",
    price: 250,
    img: "./images/carrot-juice.jpg",
    desc: `' `,
  },
  {
    id: 36,
    title: "Apple Juice",
    category: "Cold Drinks",
    price: 350,
    img: "./images/apple-juice.jpg",
    desc: `' `,
  },
  {
    id: 38,
    title: "Cocktail",
    category: "Cold Drinks",
    price: 250,
    img: "./images/cocktails.jpg",
    desc: `' `,
  },
  {
    id: 39,
    title: "Customer Customs (Ask your servers)",
    category: "Cold Drinks",
    price: 350,
    img: "./images/custom.png",
    desc: `' `,
  },
  {
    id: 41,
    title: "Madafu Juice",
    category: "Cold Drinks",
    price: 200,
    img: "./images/madafu.jpg",
    desc: ``,
  },
  {
    id: 42,
    title: "Mango Passion Juice",
    category: "Cold Drinks",
    price: 350,
    img: "./images/mango_passion.jpg",
    desc: ``,
  },
  {
    id: 43,
    title: "Paw Paw Juice",
    category: "Cold Drinks",
    price: 250,
    img: "./images/papaya.jpg",
    desc: ``,
  },
  {
    id: 44,
    title: "Pineapple Passion",
    category: "Cold Drinks",
    price: 250,
    img: "./images/pineapple_passion.jpg",
    desc: ``,
  },
  {
    id: 45,
    title: "Water Melon Juice",
    category: "Cold Drinks",
    price: 200,
    img: "./images/watermelon-juice.jpg",
    desc: ``,
  },
  {
    id: 46,
    title: "Water Lemonade",
    category: "Cold Drinks",
    price: 250,
    img: "./images/water-lemonade.jpeg",
    desc: ``,
  },
  {
    id: 48,
    title: "Classic Lemonade",
    category: "Cold Drinks",
    price: 250,
    img: "./images/classic.jpg",
    desc: ``,
  },
  {
    id: 49,
    title: "Orange Juice (imported)",
    category: "Cold Drinks",
    price: 250,
    img: "./images/Orange_Juice.webp",
    desc: ``,
  },
  {
    id: 50,
    title: "Green Detox",
    category: "Cold Drinks",
    price: 300,
    img: "./images/Green_detox.webp",
    desc: ``,
  },
  {
    id: 51,
    title: "Avocado Explosion (Contains Dairy)",
    category: "Cold Drinks",
    price: 350,
    img: "./images/avocado.jpg",
    desc: ``,
  },
  {
    id: 52,
    title: "Banana Storm (Contains Nuts and Dairy)",
    category: "Cold Drinks",
    price: 350,
    img: "./images/banana_juice.jpg",
    desc: ``,
  },
  {
    id: 53,
    title: "Mango Delight",
    category: "Cold Drinks",
    price: 350,
    img: "./images/mango-juice.jpg",
    desc: ``,
  },
  {
    id: 54,
    title: "Mango Sunset (Contains Dairy)",
    category: "Cold Drinks",
    price: 350,
    img: "./images/mango-sunset.webp",
    desc: ``,
  },
  {
    id: 55,
    title: "Tropical Thunder (Purely Fruits)",
    category: "Cold Drinks",
    price: 350,
    img: "./images/tropical_thunder.jpg",
    desc: ``,
  },
  {
    id: 56,
    title: "Pina Colada (Madafu & Pineapple)",
    category: "Cold Drinks",
    price: 400,
    img: "./images/pina-colada.jpeg",
    desc: ``,
  },
  {
    id: 57,
    title: "Vanilla Shake",
    category: "Cold Drinks",
    price: 400,
    img: "./images/vanilla-shake.jpg",
    desc: ``,
  },
  {
    id: 58,
    title: "Chocolate",
    category: "Cold Drinks",
    price: 400,
    img: "./images/hot-chocolate.webp",
    desc: ``,
  },
  {
    id: 59,
    title: "Strawberry",
    category: "Cold Drinks",
    price: 400,
    img: "./images/Strawberrymilkshake.jpg",
    desc: ``,
  },
  {
    id: 60,
    title: "Banana Shake",
    category: "Cold Drinks",
    price: 400,
    img: "./images/banana_shake.jpg",
    desc: ``,
  },
  {
    id: 61,
    title: "Mango Shake",
    category: "Cold Drinks",
    price: 400,
    img: "./images/mango-milkshake-4.webp",
    desc: ``,
  },
  {
    id: 62,
    title: "Peanut Shake",
    category: "Cold Drinks",
    price: 400,
    img: "./images/Peanut-Butter-Milkshake-5-of-5.jpg",
    desc: ``,
  },
  {
    id: 63,
    title: "Any Ice Cream",
    category: "Cold Drinks",
    price: 200,
    img: "./images/ice-cream-scoop.webp",
    desc: `(1 Scoop)`,
  },
  {
    id: 64,
    title: "Yogurt",
    category: "Cold Drinks",
    price: 300,
    img: "./images/yogurt.avif",
    desc: ``,
  },
  {
    id: 65,
    title: "Ice Tea",
    category: "Cold Drinks",
    price: 250,
    img: "./images/iced-tea-recipe-1-500x500.webp",
    desc: ``,
  },
  {
    id: 66,
    title: "Iced Coffee",
    category: "Cold Drinks",
    price: 250,
    img: "./images/Iced-coffee.webp",
    desc: `White or Black`,
  },
  {
    id: 67,
    title: "Iced Caramel, Mocha, Latte, Vanilla",
    category: "Cold Drinks",
    price: 350,
    img: "./images/Iced-caramel.jpg",
    desc: ``,
  },
  {
    id: 68,
    title: "Iced Dawa",
    category: "Cold Drinks",
    price: 300,
    img: "./images/iced-dawa.jpg",
    desc: ``,
  },
  {
    id: 69,
    title: "Mineral Water ",
    category: "Cold Drinks",
    price: '',
    img: "./images/water.jpg",
    desc: `500 ml - 100, 1ltr - 150`,
  },
  {
    id: 70,
    title: "Soda",
    category: "Cold Drinks",
    price: 100,
    img: "./images/soda.jpg",
    desc: ``,
  },
  {
    id: 71,
    title: "Home Made Granola",
    category: "Breakfast",
    price: 400,
    img: "./images/easy-homemade-granola-recipe.jpg",
    desc: ``,
  },
  {
    id: 72,
    title: "Uji Power",
    category: "Breakfast",
    price: 350,
    img: "./images/uji-power.jpg",
    desc: `(Blend of Nduma, Millet Peanut, Pumkin) served with honey aside`,
  },
  {
    id: 73,
    title: "Nduma",
    category: "Breakfast",
    price: 150,
    img: "./images/nduma.jpg",
    desc: ``,
  },
  {
    id: 74,
    title: "Githeri",
    category: "Breakfast",
    price: 200,
    img: "./images/githeri.jpg",
    desc: ``,
  },
  {
    id: 75,
    title: "Egg N Toast",
    category: "Breakfast",
    price: 250,
    img: "./images/egg-in-a-hole-1.jpg",
    desc: ``,
  },
  {
    id: 76,
    title: "Two Eggs (your way)",
    category: "Breakfast",
    price: 150,
    img: "./images/egg2.jpg",
    desc: ``,
  },
  {
    id: 77,
    title: "Egg Sausage and Toast",
    category: "Breakfast",
    price: 400,
    img: "./images/egg-sausage-toast.jpg",
    desc: ``,
  },
  {
    id: 78,
    title: "Countryside Breakfast",
    category: "Breakfast",
    price: 700,
    img: "./images/countryside.jpeg",
    desc: `2 eggs done your way, 2 sausages, 2 samosas, Toast, and a cup of Tea or Coffee.`,
  },
  {
    id: 79,
    title: "Rolex",
    category: "Breakfast",
    price: 250,
    img: "./images/rolex.jpg",
    desc: ``,
  },
  {
    id: 80,
    title: "Pancake (2pc)",
    category: "Breakfast",
    price: 200,
    img: "./images/pancakes2.jpg",
    desc: ``,
  },
  {
    id: 81,
    title: "Egg & Cheese Omelette",
    category: "Breakfast",
    price: 300,
    img: "./images/egg-n-cheese.jpg",
    desc: ``,
  },
  {
    id: 82,
    title: "Spanish Omelette",
    category: "Breakfast",
    price: 250,
    img: "./images/spanish.webp",
    desc: ``,
  },
  {
    id: 83,
    title: "Ham & Cheese Omelette",
    category: "Breakfast",
    price: 500,
    img: "./images/Ham-and-cheese-omelette_1.webp",
    desc: ``,
  },
  {
    id: 84,
    title: "Onion and Sausage",
    category: "Breakfast",
    price: 400,
    img: "./images/onion-sausage.jpg",
    desc: `Contains Organic Egg & Toast of your choice.`,
  },
  {
    id: 85,
    title: "Muffins (Assorted)",
    category: "Bakery Items",
    price: 120,
    img: "./images/Muffins_(Assorted).jpg",
    desc: ``,
  },
  {
    id: 86,
    title: "Macadamia Cookies",
    category: "Bakery Items",
    price: 250,
    img: "./images/macadamia-cookies.jpg",
    desc: ``,
  },
  {
    id: 87,
    title: "Vanilla Cake",
    category: "Bakery Items",
    price: 150,
    img: "./images/My-best-Vanilla-Cake_9.webp",
    desc: ``,
  },
  {
    id: 88,
    title: "Lemon Ginger Cookies",
    category: "Bakery Items",
    price: 250,
    img: "./images/lemon-ginger-cookies.jpg",
    desc: ``,
  },
  {
    id: 89,
    title: "Banana Bread",
    category: "Bakery Items",
    price: 150,
    img: "./images/homemade-banana-bread.jpg",
    desc: ``,
  },
  {
    id: 90,
    title: "Love Cookies",
    category: "Bakery Items",
    price: 250,
    img: "./images/lovecookies.jpg",
    desc: ``,
  },
  {
    id: 91,
    title: "Pancake",
    category: "Bakery Items",
    price: 150,
    img: "./images/pancakes2.jpg",
    desc: ``,
  },
  {
    id: 92,
    title: "Oats Cookies",
    category: "Bakery Items",
    price: 250,
    img: "./images/oatmeal-cookies.jpg",
    desc: ``,
  },
  {
    id: 93,
    title: "Pina colada Cookies",
    category: "Bakery Items",
    price: 250,
    img: "./images/pina-colada-crumbl-copycat-cookie.jpg",
    desc: ``,
  },
  {
    id: 94,
    title: "Countryside Cheese Burger",
    category: "Burgers & Sandwiches",
    price: 650,
    img: "./images/classic-beef-cheeseburgers-horizontal.jpg",
    desc: `Beef Patty Ona Bun, Cheese, Grilled Onions, Lettuce and Tomatoes topped with Mayonnaise, Mustard and Ketchup Served with Chips.`,
  },
  {
    id: 95,
    title: "Countryside Chicken Cheese Burger",
    category: "Burgers & Sandwiches",
    price: 650,
    img: "./images/chicken.jpg",
    desc: `Chickenstrips Ona Bun, Cheese, Grilled Onions, Lettuce and Tomatoes, topped with Mayonnaise, Mustard and Ketchup, Served with Chips/ French Fries.`,
  },
  {
    id: 96,
    title: "Ham & Cheese Sandwich",
    category: "Burgers & Sandwiches",
    price: 600,
    img: "./images/ham-and-cheese.jpg",
    desc: ``,
  },
  {
    id: 97,
    title: "Chicken & Cheese Sandwich",
    category: "Burgers & Sandwiches",
    price: 550,
    img: "./images/chicken&cheese.jpg",
    desc: ``,
  },
  {
    id: 98,
    title: "BBQ Chicken Sandwich",
    category: "Burgers & Sandwiches",
    price: 550,
    img: "./images/BBQ-Chicken.jpg",
    desc: ``,
  },
  {
    id: 99,
    title: "Avocado Cheese & Tomato Sandwich",
    category: "Burgers & Sandwiches",
    price: 500,
    img: "./images/avocado-tomato-grilled-cheese-sandwiches-ck-x.jpg",
    desc: `Served with Chips and your choice of White or Brown Bread.`,
  },
  {
    id: 100,
    title: "1/4 Chicken Served with Chips and Salsa",
    category: "Quick Bite & Snacks",
    price: 600,
    img: "./images/chicken-salsa.jpg",
    desc: ``,
  },
  {
    id: 101,
    title: "3 Chicken Lolli Pop",
    category: "Quick Bite & Snacks",
    price: 750,
    img: "./images/chicken-lollipops-1.jpg",
    desc: `Served with Spiced Chips and Hot & Sweet Sauce.`,
  },
  {
    id: 102,
    title: "Chicken Nuggets",
    category: "Quick Bite & Snacks",
    price: 600,
    img: "./images/Chicken_Nuggets.jpg",
    desc: ``,
  },
  {
    id: 103,
    title: "Samosas (2pcs)",
    category: "Quick Bite & Snacks",
    price: 150,
    img: "./images/Samosas_(2pcs).jpg",
    desc: ``,
  },
  {
    id: 104,
    title: "Sausages (2pcs)",
    category: "Quick Bite & Snacks",
    price: 150,
    img: "./images/Sausages.jpg",
    desc: ``,
  },
  {
    id: 105,
    title: "Samosa Special",
    category: "Quick Bite & Snacks",
    price: 250,
    img: "./images/samosa-with-fries.jpg",
    desc: `served with small chips`,
  },
  {
    id: 106,
    title: "Sausage Special",
    category: "Quick Bite & Snacks",
    price: 250,
    img: "./images/sausage-special.jpg",
    desc: `served with small chips`,
  },
  {
    id: 107,
    title: "Kebab",
    category: "Quick Bite & Snacks",
    price: 180,
    img: "./images/kebab.jpg",
    desc: ``,
  },
  {
    id: 108,
    title: "Kebab Special",
    category: "Quick Bite & Snacks",
    price: 300,
    img: "./images/kebab-with-fries.jpg",
    desc: ``,
  },
  {
    id: 109,
    title: "Chips (Regular or Spiced)",
    category: "Quick Bite & Snacks",
    price: 250,
    img: "./images/french-fries.jpg",
    desc: ``,
  },
  {
    id: 110,
    title: "Chips Masala",
    category: "Quick Bite & Snacks",
    price: 300,
    img: "./images/masala-chips-7.jpg",
    desc: ``,
  },
  {
    id: 111,
    title: "Loaded Home Fries",
    category: "Quick Bite & Snacks",
    price: 700,
    img: "./images/cheese-fries-1.jpg",
    desc: `Roasted Potato Wedges, Barbecue Sauce, Grated Cheese, Salsa & Chicken Strips. `,
  },
  {
    id: 112,
    title: "Pousin Chips",
    category: "Quick Bite & Snacks",
    price: 270,
    img: "./images/poussin.jpg",
    desc: ``,
  },
  {
    id: 113,
    title: "Butter Nut Soup",
    category: "Main Course",
    price: 250,
    img: "./images/Butternut-Squash-Soup-4.jpg",
    desc: ``,
  },
  {
    id: 114,
    title: "Soup of the Day (Ask your server)",
    category: "Main Course",
    price: 350,
    img: "./images/chicken-noodle-soup-index-644c2bec1ce0c.jpg",
    desc: ``,
  },
  {
    id: 115,
    title: "Beef Stew with Spinach & Salsa",
    category: "Main Course",
    price: 550,
    img: "./images/beef-stew.jpg",
    desc: ``,
  },
  {
    id: 116,
    title: "Beef Wet Fry (Fillet Steak)",
    category: "Main Course",
    price: 750,
    img: "./images/beef-fillet.jpg",
    desc: `Served with Ugali spinach & Salsa.`,
  },
  {
    id: 117,
    title: "Grilled Pepper Steak",
    category: "Main Course",
    price: 1000,
    img: "./images/Grilled-Peppered-Steak.jpg",
    desc: `With your choice of veg Rice, Chapati, Chips, Veg Mix  Ugali, Mukimo or Githeri. `,
  },
  {
    id: 118,
    title: "Grilled Fillet Steak",
    category: "Main Course",
    price: 800,
    img: "./images/grilled-fillet.jpg",
    desc: `With your choice of veg Rice, 2 Chapatis, Chips, Veg Mix, Ugali, Mukimo or Githeri.`,
  },
  {
    id: 119,
    title: "1Kg Oven Roasted Goat (Choma).",
    category: "Main Course",
    price: 1000,
    img: "./images/Slow-roasted-goat-leg-slices.webp",
    desc: `Served with Salsa to Add Starch Refer to Side Orders.`,
  },
  {
    id: 120,
    title: "1/4 Goat Wet Fry With Spinach & Salsa.",
    category: "Main Course",
    price: 500,
    img: "./images/goat-wet.jpg",
    desc: ``,
  },
  ,
  {
    id: 121,
    title: "Oriental Chicken Salad.",
    category: "Salads",
    price: 700,
    img: "./images/oriental-salad.jpg",
    desc: ``,
  },
  ,
  {
    id: 122,
    title: "Breaded Chicken Salad.",
    category: "Salads",
    price: 700,
    img: "./images/crispy-chicken-salad.jpg",
    desc: ``,
  },
  ,
  {
    id: 123,
    title: "Garden Salad",
    category: "Salads",
    price: 300,
    img: "./images/Garden-Salad_47-SQ.webp",
    desc: ``,
  },
  ,
  {
    id: 124,
    title: "Apple & Cashew-nut Salad",
    category: "Salads",
    price: 700,
    img: "./images/apple-cashewnut.jpg",
    desc: `Has light Mustard dressing, purely for vegetarians.`,
  },
  {
    id: 125,
    title: "Fruit Salad Plain",
    category: "Salads",
    price: 150,
    img: "./images/fruit-salad.webp",
    desc: ` `,
  },
  {
    id: 126,
    title: "Fruit Salad (Yogurt, Nuts & Honey)",
    category: "Salads",
    price: 300,
    img: "./images/Fruit-Yogurt-Nut-Plate-4.jpg",
    desc: ``,
  },
  {
    id: 127,
    title: "Full Fish",
    category: "Main Course",
    price: 700,
    img: "./images/full-fish.jpg",
    desc: `Served with Ugali and Spinach.`,
  },
  {
    id: 128,
    title: "Full Fillet",
    category: "Main Course",
    price: 800,
    img: "./images/full-fillet.jpg",
    desc: `Served with Fish Sauce, Chips, and Salad.`,
  },
  {
    id: 129,
    title: "Fish Fingers 6pcs",
    category: "Main Course",
    price: 700,
    img: "./images/fish-fingers.jpg",
    desc: `Served with Tarter Sauce and Chips.`,
  },
  {
    id: 130,
    title: "Swahili Fish Curry",
    category: "Main Course",
    price: 700,
    img: "./images/swahili-fish-curry.jpg",
    desc: `Served with Rice or Chapati & Salsa`,
  },
  {
    id: 131,
    title: "Beef Pilau",
    category: "Main Course",
    price: 550,
    img: "./images/East-african-pilau-pelau.jpg",
    desc: `Served with steamed Spinach and Beef Stew.`,
  },
  {
    id: 132,
    title: "Chicken Pilau",
    category: "Main Course",
    price: 550,
    img: "./images/Chicken-pilau-rice-1-2.jpg",
    desc: `Served with steamed cabbage and soup.`,
  },
  {
    id: 133,
    title: "Managu",
    category: "Main Course",
    price: 300,
    img: "./images/Ugali-mboga.webp",
    desc: `Served with ugali and salsa.`,
  },
  {
    id: 134,
    title: "Chicken Kienyeji",
    category: "Main Course",
    price: 550,
    img: "./images/kienyeji.jpg",
    desc: `Served with your choice of Matoke, 2 chapati, Veg Rice, Ugali, Mukimo, or Githeri.`,
  },
  {
    id: 135,
    title: "Goat Platter (4 Servings)",
    category: "Main Course",
    price: 2000,
    img: "./images/goat-platter.jpg",
    desc: `Has: Nduma, Matoke, Spinach & Soup, (No Cooking Oil)`,
  },
  {
    id: 136,
    title: "Chicken Kienyeji Platter (4 Servings)",
    category: "Main Course",
    price: 2000,
    img: "./images/fried-kienyeji-chicken-recipe-main-photo.jpg",
    desc: `Has: Nduma, Matoke, Spinach & Soup (No Cooking Oil)`,
  },
  {
    id: 137,
    title: "For Specials, Add Steamed Vegetable, Mukimo, Ugali, or Chapati",
    category: "Main Course",
    price: 150,
    img: "./images/assorted.webp",
    desc: ``,
  },
  {
    id: 138,
    title: "Full Chicken Kienyeji",
    category: "Main Course",
    price: 1600,
    img: "./images/kienyeji.jpg",
    desc: `add your choice of starch 150.`,
  },
  {
    id: 139,
    title: "Roast Chicken",
    category: "Main Course",
    price: 500,
    img: "./images/roast_chicken.jpg",
    desc: `Served with chips and Salad.`,
  },
  {
    id: 140,
    title: "Grilled Chicken Breast Boneless with Pepper Sauce",
    category: "Main Course",
    price: 800,
    img: "./images/Air-Fryer-Chicken-Breast-3.jpg",
    desc: `Served with Chips and Salad.`,
  },
  {
    id: 141,
    title: "Chicken Swahili",
    category: "Main Course",
    price: 700,
    img: "./images/swahili-chicken.jpg",
    desc: `Served with vegetable rice and Salad.`,
  },
  {
    id: 142,
    title: "Chicken Curry",
    category: "Main Course",
    price: 650,
    img: "./images/46822-indian-chicken-curry-ii.jpg",
    desc: `Served with salsa, Guacamole & (Your Choice of chapati, Veg Rice, Matoke & Mukimo).`,
  },
  {
    id: 143,
    title: "Chicken Masala",
    category: "Main Course",
    price: 650,
    img: "./images/chicken-masala.jpg",
    desc: `Served with Cumin Rice and Salsa.`,
  },
  {
    id: 144,
    title: "Wet Fried Chicken",
    category: "Main Course",
    price: 600,
    img: "./images/kienyeji-wet-fry.jpg",
    desc: `Served with spinach & your Choice of Ugali, Mukimo & Chapati.`,
  },
  {
    id: 145,
    title: "Ugali - White",
    category: "Sides",
    price: 70,
    img: "./images/white-ugali-recipe-main-photo.jpg",
    desc: ``,
  }, 
  {
    id: 146,
    title: "Ugali Brown",
    category: "Sides",
    price: 100,
    img: "./images/ugali-brown.jpg",
    desc: ``,
  }, 
  {
    id: 147,
    title: "Vegetable Fried Rice",
    category: "Sides",
    price: 200,
    img: "./images/230515_Vegetable-Fried-Rice_550.jpg",
    desc: ``,
  },
  {
    id: 148,
    title: "Pilau",
    category: "Sides",
    price: 200,
    img: "./images/pilau.jpg",
    desc: ``,
  },
  {
    id: 149,
    title: "Mukimo Plain",
    category: "Sides",
    price: 200,
    img: "./images/Kienyeji.webp",
    desc: ``,
  },
  {
    id: 150,
    title: "Honey Peanut",
    category: "Sides",
    price: 80,
    img: "./images/honey-peanuts.jpg",
    desc: ``,
  },
  {
    id: 151,
    title: "Matoke",
    category: "Sides",
    price: 200,
    img: "./images/Matoke-Recipe-8.jpg",
    desc: ``,
  },
  {
    id: 152,
    title: "Chapati (2)",
    category: "Sides",
    price: 100,
    img: "./images/chapo.jpg",
    desc: ``,
  },

];


const btnContainer = document.querySelector('.btn-container');
const sectionCenter = document.querySelector('.section-center');

const btn = document.getElementById("search-btn");
const userInput = document.getElementById("search-item");
const form = document.getElementsByTagName("form")[0];

let searchTerm = ""; 

let searchTab = document.querySelector('.searchTab')

btn.addEventListener('click', (event) => {
  event.preventDefault();
  searchTerm = userInput.value;
  const filteredItems = filterMenu(searchTerm);

  let displayMenu = filteredItems.map(function (item) { // Add this line for debugging
    return `<article class="menu-item">
      <img src=${item.img} class="photo">
      <div class="item-info">
        <header>
          <h4 class="title-name">${item.title}</h4>
          <h4 class="price"> Ksh. ${item.price}</h4>
        </header>
        <p class="item-text">${item.desc}</p>
      </div>
    </article>`;
  }).join('');
  
  searchTab.innerHTML = displayMenu;
});

//load all items 
window.addEventListener('DOMContentLoaded', function(){
  displayMenuItems(menu); 
  displayMenuButtons();
});

function displayMenuButtons(){
  const categories = menu.reduce(function (values, item) {
    if(!values.includes(item.category)){
      values.push(item.category);
    }
    return values;
  }, ['all']);
  const categoryBtn = categories.map(function (category){
    return `<button class="filter-btn" type="button" data-id="${category}">${category}</button>`;
  }).join('');
  btnContainer.innerHTML = categoryBtn;
  const filterBtns = document.querySelectorAll('.filter-btn');
  
  //filter buttons 
  filterBtns.forEach(function (btn) {
    btn.addEventListener('click', function(e){
      const category = e.currentTarget.dataset.id;
      const menuCategory = menu.filter(function (menuItem){
        if (menuItem.category == category){
          return menuItem;
        }
      });
      if (category === 'all'){
        displayMenuItems(menu);
      } else {
        displayMenuItems(menuCategory);
      }
    });
  });
}

function filterMenu(searchTerm) {
  const search = searchTerm.toLowerCase();
  const filteredMenu = menu.filter(item => {
    return item.title.toLowerCase().includes(search) || item.category.toLowerCase().includes(search);
  });

  return filteredMenu; // Return the filtered array
}

function displayMenuItems(menuItems){
  let displayMenu = menuItems.map(function (item){
    return `<article class="menu-item">
    <img src=${item.img} class="photo">
    <div class="item-info">
      <header>
      <h4 class="title-name">${item.title}</h4>
      <h4 class="price"> Ksh. ${item.price}</h4>
      </header>
      <p class="item-text">${item.desc}</p>
    </div>
  </article>`;
  }).join('');
  
  sectionCenter.innerHTML = displayMenu;
}

